#include "Bridge.h"

#include <QWebSocket>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QJsonValue>
#include <QFile>
#include <QDir>
#include <QStandardPaths>
#include <QUrl>
#include <QUrlQuery>
#include <QDebug>

Bridge::Bridge(QObject *parent)
    : QObject(parent)
    , m_socket(new QWebSocket(QString(), QWebSocketProtocol::VersionLatest, this))
{
    connect(m_socket, &QWebSocket::connected, this, &Bridge::onConnected);
    connect(m_socket, &QWebSocket::disconnected, this, &Bridge::onDisconnected);
    connect(m_socket, &QWebSocket::textMessageReceived, this, &Bridge::onTextMessageReceived);
    connect(m_socket, QOverload<QAbstractSocket::SocketError>::of(&QWebSocket::errorOccurred),
            this, &Bridge::onSocketError);
}

Bridge::~Bridge() = default;

QString Bridge::readControlToken()
{
    // ~/.config/jarvis/control_token  (0600, auto-generated by jarvisd on first start).
    QString base = QStandardPaths::writableLocation(QStandardPaths::ConfigLocation);
    if (base.isEmpty())
        base = QDir::homePath() + QStringLiteral("/.config");
    const QString path = base + QStringLiteral("/jarvis/control_token");

    QFile f(path);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
        return QString();
    QString tok = QString::fromUtf8(f.readAll()).trimmed();
    return tok;
}

QString Bridge::controlUrl()
{
    QUrl url;
    url.setScheme(QStringLiteral("ws"));
    url.setHost(QStringLiteral("127.0.0.1"));
    url.setPort(8795);
    url.setPath(QStringLiteral("/control/ws"));

    QUrlQuery q;
    q.addQueryItem(QStringLiteral("token"), readControlToken());
    url.setQuery(q);
    return url.toString();
}

void Bridge::setStatus(const QString &s)
{
    if (m_status == s)
        return;
    m_status = s;
    emit statusChanged();
}

void Bridge::connectToDaemon()
{
    if (m_connected) {
        return;
    }
    const QString tok = readControlToken();
    if (tok.isEmpty()) {
        setStatus(QStringLiteral("no token"));
        emit errorOccurred(QStringLiteral("control_token not found at ~/.config/jarvis/control_token"));
        // Still attempt connect; daemon may reject, which surfaces a clear error.
    }
    setStatus(QStringLiteral("connecting"));
    m_socket->open(QUrl(controlUrl()));
}

void Bridge::onConnected()
{
    m_connected = true;
    emit connectedChanged();
    setStatus(QStringLiteral("connected"));
    // Liveness check per Contract A.
    request(QStringLiteral("ping"), {});
}

void Bridge::onDisconnected()
{
    const bool was = m_connected;
    m_connected = false;
    if (was)
        emit connectedChanged();
    setStatus(QStringLiteral("disconnected"));
}

void Bridge::onSocketError()
{
    setStatus(QStringLiteral("error"));
    emit errorOccurred(m_socket->errorString());
}

int Bridge::nextId()
{
    return ++m_idCounter;
}

void Bridge::send(const QString &method, const QVariantMap &params, int id)
{
    QJsonObject obj;
    obj.insert(QStringLiteral("v"), 1);
    obj.insert(QStringLiteral("id"), id);
    obj.insert(QStringLiteral("method"), method);
    obj.insert(QStringLiteral("params"), QJsonObject::fromVariantMap(params));

    const QByteArray payload = QJsonDocument(obj).toJson(QJsonDocument::Compact);
    if (m_socket->state() != QAbstractSocket::ConnectedState) {
        emit errorOccurred(QStringLiteral("not connected: dropped ") + method);
        return;
    }
    m_socket->sendTextMessage(QString::fromUtf8(payload));
}

int Bridge::request(const QString &method, const QVariantMap &params)
{
    const int id = nextId();
    m_pending.insert(id, method);
    send(method, params, id);
    return id;
}

void Bridge::createSession(const QString &profile, const QString &brain, const QString &model)
{
    QVariantMap params;
    params.insert(QStringLiteral("profile"), profile.isEmpty() ? QStringLiteral("coder") : profile);
    params.insert(QStringLiteral("brain"), brain.isEmpty() ? QStringLiteral("codex") : brain);
    if (!model.isEmpty())
        params.insert(QStringLiteral("model"), model);
    request(QStringLiteral("session.create"), params);
}

void Bridge::sendMessage(const QString &text)
{
    if (m_sessionId.isEmpty()) {
        emit errorOccurred(QStringLiteral("no active session; create one first"));
        return;
    }
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), m_sessionId);
    params.insert(QStringLiteral("text"), text);
    request(QStringLiteral("session.send"), params);
}

void Bridge::cancelSession()
{
    if (m_sessionId.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), m_sessionId);
    request(QStringLiteral("session.cancel"), params);
}

void Bridge::respondApproval(const QString &approvalId, const QString &decision)
{
    if (m_sessionId.isEmpty()) {
        emit errorOccurred(QStringLiteral("no active session for approval response"));
        return;
    }
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), m_sessionId);
    params.insert(QStringLiteral("approval_id"), approvalId);
    params.insert(QStringLiteral("decision"), decision);
    request(QStringLiteral("approval.respond"), params);
}

void Bridge::listModels(const QString &brain)
{
    QVariantMap params;
    params.insert(QStringLiteral("brain"), brain.isEmpty() ? QStringLiteral("codex") : brain);
    request(QStringLiteral("model.list"), params);
}

void Bridge::onTextMessageReceived(const QString &message)
{
    QJsonParseError perr;
    const QJsonDocument doc = QJsonDocument::fromJson(message.toUtf8(), &perr);
    if (perr.error != QJsonParseError::NoError || !doc.isObject()) {
        emit errorOccurred(QStringLiteral("malformed frame: ") + perr.errorString());
        return;
    }
    const QJsonObject obj = doc.object();

    // Unsolicited event frame.
    if (obj.value(QStringLiteral("event")).toString() == QStringLiteral("session.event")) {
        const QJsonObject data = obj.value(QStringLiteral("data")).toObject();
        const QString sid = data.value(QStringLiteral("session_id")).toString();
        const QJsonObject ev = data.value(QStringLiteral("ev")).toObject();

        QVariantMap evMap = ev.toVariantMap();
        // Fold the session id in so the UI can route by session.
        evMap.insert(QStringLiteral("session_id"), sid);
        emit sessionEvent(evMap);
        return;
    }

    // Response frame (has an id).
    if (obj.contains(QStringLiteral("id")) && !obj.value(QStringLiteral("id")).isNull()) {
        const int id = obj.value(QStringLiteral("id")).toInt();
        const bool ok = obj.value(QStringLiteral("ok")).toBool();
        const QVariantMap result = obj.value(QStringLiteral("result")).toObject().toVariantMap();
        const QVariantMap error = obj.value(QStringLiteral("error")).toObject().toVariantMap();
        handleResponse(id, ok, result, error);
        return;
    }
}

void Bridge::handleResponse(int id, bool ok, const QVariantMap &result, const QVariantMap &error)
{
    const QString method = m_pending.take(id);

    if (!ok) {
        const QString msg = error.value(QStringLiteral("message")).toString();
        const QString code = error.value(QStringLiteral("code")).toString();
        emit errorOccurred(QStringLiteral("%1 failed: [%2] %3")
                               .arg(method.isEmpty() ? QStringLiteral("request") : method, code, msg));
        return;
    }

    if (method == QStringLiteral("session.create")) {
        const QString sid = result.value(QStringLiteral("session_id")).toString();
        if (!sid.isEmpty()) {
            m_sessionId = sid;
            emit sessionIdChanged();
            setStatus(QStringLiteral("session ready"));
        }
    } else if (method == QStringLiteral("model.list")) {
        QStringList models;
        const QVariant raw = result.value(QStringLiteral("models"));
        for (const QVariant &v : raw.toList())
            models << v.toString();
        const QString brain = result.value(QStringLiteral("brain")).toString();
        emit modelsListed(brain, models);
    }
    // ping / session.send / session.cancel / approval.respond: ack only.
}
