#include "Bridge.h"
#include "FrameProvider.h"

#include <QWebSocket>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QJsonValue>
#include <QFile>
#include <QDir>
#include <QFileInfo>
#include <QStandardPaths>
#include <QUrl>
#include <QUrlQuery>
#include <QTimer>
#include <QNetworkAccessManager>
#include <QNetworkRequest>
#include <QNetworkReply>
#include <QFileSystemWatcher>
#include <QDebug>

Bridge::Bridge(QObject *parent)
    : QObject(parent)
    , m_socket(new QWebSocket(QString(), QWebSocketProtocol::VersionLatest, this))
{
    connect(m_socket, &QWebSocket::connected, this, &Bridge::onConnected);
    connect(m_socket, &QWebSocket::disconnected, this, &Bridge::onDisconnected);
    connect(m_socket, &QWebSocket::textMessageReceived, this, &Bridge::onTextMessageReceived);
    connect(m_socket, QOverload<QAbstractSocket::SocketError>::of(&QWebSocket::errorOccurred),
            this, &Bridge::onSocketError);

    // ---- COMPUTER page: live-video poller (engine GET /video/frame) ---------
    m_net = new QNetworkAccessManager(this);
    m_videoBearer = computeUseBearer();
    m_frameTimer = new QTimer(this);
    m_frameTimer->setInterval(125);   // ~8 fps local preview poll
    connect(m_frameTimer, &QTimer::timeout, this, &Bridge::pollFrame);
}

Bridge::~Bridge()
{
    stopPointerTail();
}

QString Bridge::readControlToken()
{
    // ~/.config/jarvis/control_token  (0600, auto-generated by jarvisd on first start).
    QString base = QStandardPaths::writableLocation(QStandardPaths::ConfigLocation);
    if (base.isEmpty())
        base = QDir::homePath() + QStringLiteral("/.config");
    const QString path = base + QStringLiteral("/jarvis/control_token");

    QFile f(path);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
        return QString();
    QString tok = QString::fromUtf8(f.readAll()).trimmed();
    return tok;
}

QString Bridge::computeUseBearer()
{
    // The per-session computer-use engine inherits the tailnet bearer from
    // ~/.computer-use/config.yaml (key: bearer_token / token). We only need it to
    // poll GET /video/frame for the local preview. Parse leniently — it is a tiny
    // YAML file of "key: value" lines, so a regex-free line scan is enough and
    // avoids pulling in a YAML dependency.
    const QString path = QDir::homePath() + QStringLiteral("/.computer-use/config.yaml");
    QFile f(path);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
        return QString();
    const QStringList lines = QString::fromUtf8(f.readAll()).split(QLatin1Char('\n'));
    for (const QString &raw : lines) {
        const QString line = raw.trimmed();
        for (const QString &key : { QStringLiteral("bearer_token"),
                                    QStringLiteral("bearer"),
                                    QStringLiteral("token") }) {
            if (line.startsWith(key + QLatin1Char(':'))) {
                QString val = line.mid(key.size() + 1).trimmed();
                if (val.startsWith(QLatin1Char('"')) && val.endsWith(QLatin1Char('"'))
                    && val.size() >= 2)
                    val = val.mid(1, val.size() - 2);
                if (val.startsWith(QLatin1Char('\'')) && val.endsWith(QLatin1Char('\''))
                    && val.size() >= 2)
                    val = val.mid(1, val.size() - 2);
                if (!val.isEmpty())
                    return val;
            }
        }
    }
    return QString();
}

QString Bridge::controlUrl()
{
    QUrl url;
    url.setScheme(QStringLiteral("ws"));
    url.setHost(QStringLiteral("127.0.0.1"));
    url.setPort(8795);
    url.setPath(QStringLiteral("/control/ws"));

    QUrlQuery q;
    q.addQueryItem(QStringLiteral("token"), readControlToken());
    url.setQuery(q);
    return url.toString();
}

void Bridge::setStatus(const QString &s)
{
    if (m_status == s)
        return;
    m_status = s;
    emit statusChanged();
}

void Bridge::connectToDaemon()
{
    if (m_connected) {
        return;
    }
    const QString tok = readControlToken();
    if (tok.isEmpty()) {
        setStatus(QStringLiteral("no token"));
        emit errorOccurred(QStringLiteral("control_token not found at ~/.config/jarvis/control_token"));
        // Still attempt connect; daemon may reject, which surfaces a clear error.
    }
    setStatus(QStringLiteral("connecting"));
    m_socket->open(QUrl(controlUrl()));
}

void Bridge::onConnected()
{
    m_connected = true;
    emit connectedChanged();
    setStatus(QStringLiteral("connected"));
    // Liveness check per Contract A.
    request(QStringLiteral("ping"), {});
}

void Bridge::onDisconnected()
{
    const bool was = m_connected;
    m_connected = false;
    if (was)
        emit connectedChanged();
    setStatus(QStringLiteral("disconnected"));
}

void Bridge::onSocketError()
{
    setStatus(QStringLiteral("error"));
    emit errorOccurred(m_socket->errorString());
}

int Bridge::nextId()
{
    return ++m_idCounter;
}

void Bridge::send(const QString &method, const QVariantMap &params, int id)
{
    QJsonObject obj;
    obj.insert(QStringLiteral("v"), 1);
    obj.insert(QStringLiteral("id"), id);
    obj.insert(QStringLiteral("method"), method);
    obj.insert(QStringLiteral("params"), QJsonObject::fromVariantMap(params));

    const QByteArray payload = QJsonDocument(obj).toJson(QJsonDocument::Compact);
    if (m_socket->state() != QAbstractSocket::ConnectedState) {
        emit errorOccurred(QStringLiteral("not connected: dropped ") + method);
        return;
    }
    m_socket->sendTextMessage(QString::fromUtf8(payload));
}

int Bridge::request(const QString &method, const QVariantMap &params, const QString &ctx)
{
    const int id = nextId();
    m_pending.insert(id, method);
    if (!ctx.isEmpty())
        m_pendingCtx.insert(id, ctx);
    send(method, params, id);
    return id;
}

void Bridge::createSession(const QString &profile, const QString &brain, const QString &model)
{
    QVariantMap params;
    params.insert(QStringLiteral("profile"), profile.isEmpty() ? QStringLiteral("coder") : profile);
    params.insert(QStringLiteral("brain"), brain.isEmpty() ? QStringLiteral("codex") : brain);
    if (!model.isEmpty())
        params.insert(QStringLiteral("model"), model);
    request(QStringLiteral("session.create"), params);
}

void Bridge::sendMessage(const QString &text)
{
    if (m_sessionId.isEmpty()) {
        emit errorOccurred(QStringLiteral("no active session; create one first"));
        return;
    }
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), m_sessionId);
    params.insert(QStringLiteral("text"), text);
    request(QStringLiteral("session.send"), params);
}

void Bridge::cancelSession()
{
    if (m_sessionId.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), m_sessionId);
    request(QStringLiteral("session.cancel"), params);
}

void Bridge::respondApproval(const QString &approvalId, const QString &decision)
{
    if (m_sessionId.isEmpty()) {
        emit errorOccurred(QStringLiteral("no active session for approval response"));
        return;
    }
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), m_sessionId);
    params.insert(QStringLiteral("approval_id"), approvalId);
    params.insert(QStringLiteral("decision"), decision);
    request(QStringLiteral("approval.respond"), params);
}

void Bridge::listModels(const QString &brain)
{
    QVariantMap params;
    params.insert(QStringLiteral("brain"), brain.isEmpty() ? QStringLiteral("codex") : brain);
    request(QStringLiteral("model.list"), params);
}

// ---- Contract A v2 ---------------------------------------------------------

void Bridge::openSession(const QString &sessionId)
{
    if (sessionId.isEmpty())
        return;
    m_sessionId = sessionId;
    emit sessionIdChanged();
    setStatus(QStringLiteral("session ready"));
    emit sessionOpened(sessionId);
    // Load this session's history so the Chat page can replay it.
    m_openingSession = true;
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), sessionId);
    request(QStringLiteral("session.history"), params, sessionId);
}

void Bridge::loadSettings()
{
    request(QStringLiteral("settings.get"), {});
}

void Bridge::saveSettings(const QVariantMap &patch)
{
    QVariantMap params;
    params.insert(QStringLiteral("patch"), patch);
    request(QStringLiteral("settings.set"), params);
}

void Bridge::listMcp()
{
    request(QStringLiteral("mcp.list"), {});
}

void Bridge::addMcp(const QVariantMap &server)
{
    request(QStringLiteral("mcp.add"), server);
}

void Bridge::removeMcp(const QString &id)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("mcp.remove"), params);
}

void Bridge::setMcpEnabled(const QString &id, bool enabled)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    params.insert(QStringLiteral("enabled"), enabled);
    request(QStringLiteral("mcp.set_enabled"), params);
}

void Bridge::testMcp(const QString &id)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("mcp.test"), params, id);
}

void Bridge::loadPlugins()
{
    request(QStringLiteral("plugins.catalog"), {});
}

void Bridge::installPlugin(const QString &id)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("plugins.install"), params);
}

void Bridge::setPluginEnabled(const QString &id, bool enabled)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    params.insert(QStringLiteral("enabled"), enabled);
    request(QStringLiteral("plugins.set_enabled"), params);
}

void Bridge::removePlugin(const QString &id)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("plugins.remove"), params);
}

void Bridge::listSessions()
{
    request(QStringLiteral("session.list"), {});
}

void Bridge::loadSessionHistory(const QString &sessionId)
{
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), sessionId);
    request(QStringLiteral("session.history"), params, sessionId);
}

// ---- Devices (pairing) -----------------------------------------------------

void Bridge::devicesPairStart()
{
    request(QStringLiteral("devices.pair_start"), {});
}

void Bridge::devicesList()
{
    request(QStringLiteral("devices.list"), {});
}

void Bridge::devicesRevoke(const QString &id)
{
    if (id.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("devices.revoke"), params);
}

// ---- Memory (Contract A v3) ------------------------------------------------

void Bridge::memoryList(int limit)
{
    QVariantMap params;
    if (limit > 0)
        params.insert(QStringLiteral("limit"), limit);
    request(QStringLiteral("memory.list"), params);
}

void Bridge::memorySearch(const QString &q)
{
    const QString query = q.trimmed();
    if (query.isEmpty()) {
        // Empty query is just a full-list refresh.
        memoryList();
        return;
    }
    QVariantMap params;
    params.insert(QStringLiteral("q"), query);
    request(QStringLiteral("memory.search"), params);
}

void Bridge::memoryAdd(const QString &text, const QStringList &tags)
{
    const QString body = text.trimmed();
    if (body.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("text"), body);
    if (!tags.isEmpty())
        params.insert(QStringLiteral("tags"), tags);
    request(QStringLiteral("memory.add"), params);
}

void Bridge::memoryRemove(const QString &id)
{
    if (id.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("memory.remove"), params);
}

// ---- Skills (Contract A v3, self-authoring) --------------------------------

void Bridge::skillsList()
{
    request(QStringLiteral("skills.list"), {});
}

void Bridge::skillGet(const QString &name)
{
    if (name.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("name"), name);
    request(QStringLiteral("skills.get"), params, name);
}

void Bridge::skillCreate(const QString &name, const QString &description,
                         const QString &body, const QString &group)
{
    const QString n = name.trimmed();
    if (n.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("name"), n);
    params.insert(QStringLiteral("description"), description.trimmed());
    params.insert(QStringLiteral("body"), body);
    if (!group.trimmed().isEmpty())
        params.insert(QStringLiteral("group"), group.trimmed());
    request(QStringLiteral("skills.create"), params);
}

void Bridge::skillInvoke(const QString &name, const QString &args)
{
    if (name.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("name"), name);
    if (!args.trimmed().isEmpty())
        params.insert(QStringLiteral("args"), args.trimmed());
    request(QStringLiteral("skills.invoke"), params, name);
}

void Bridge::skillRemove(const QString &name)
{
    if (name.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("name"), name);
    request(QStringLiteral("skills.remove"), params);
}

void Bridge::skillsToday()
{
    request(QStringLiteral("skills.today"), {});
}

// ---- COMPUTER page ---------------------------------------------------------

void Bridge::setDriving(bool d)
{
    if (m_driving == d)
        return;
    m_driving = d;
    emit drivingChanged();
    // The distinct-cursor overlay only needs the agent-pointer feed while a
    // real-screen take-over is live; tail the fallback bus accordingly.
    if (d)
        startPointerTail();
    else
        stopPointerTail();
}

void Bridge::setMirroring(bool m)
{
    if (m_mirroring == m)
        return;
    m_mirroring = m;
    emit mirroringChanged();
}

void Bridge::setCoworkerSessionId(const QString &id)
{
    if (m_coworkerSessionId == id)
        return;
    m_coworkerSessionId = id;
    emit coworkerSessionIdChanged();
}

void Bridge::startCoworker(const QString &brain, const QString &model)
{
    QVariantMap params;
    params.insert(QStringLiteral("profile"), QStringLiteral("coworker"));
    params.insert(QStringLiteral("brain"), brain.isEmpty() ? QStringLiteral("codex") : brain);
    params.insert(QStringLiteral("target"), QStringLiteral("agent"));
    if (!model.isEmpty())
        params.insert(QStringLiteral("model"), model);
    // Tag the request so the response handler knows to wire up the co-worker
    // session + auto-start the agent-desktop mirror.
    request(QStringLiteral("session.create"), params, QStringLiteral("coworker:agent"));
}

void Bridge::stopCoworker()
{
    mirrorStop();
    if (!m_coworkerSessionId.isEmpty()) {
        QVariantMap params;
        params.insert(QStringLiteral("session_id"), m_coworkerSessionId);
        request(QStringLiteral("session.cancel"), params);
    }
    setCoworkerSessionId(QString());
}

void Bridge::takeOver(const QString &brain, const QString &model)
{
    QVariantMap params;
    params.insert(QStringLiteral("profile"), QStringLiteral("coworker"));
    params.insert(QStringLiteral("brain"), brain.isEmpty() ? QStringLiteral("codex") : brain);
    params.insert(QStringLiteral("target"), QStringLiteral("real"));
    if (!model.isEmpty())
        params.insert(QStringLiteral("model"), model);
    // target="real" is approval/biometric gated by the daemon; the driving flag
    // only flips once the daemon confirms via a driving.state event.
    request(QStringLiteral("session.create"), params, QStringLiteral("coworker:real"));
}

void Bridge::releaseScreen()
{
    // Tell the daemon to end the take-over; optimistically drop the overlay so the
    // user is never left with a stuck "JARVIS IS DRIVING" banner if the daemon is
    // slow to confirm.
    QVariantMap params;
    if (!m_sessionId.isEmpty())
        params.insert(QStringLiteral("session_id"), m_sessionId);
    request(QStringLiteral("session.set_target"), params);   // best-effort; daemon may ignore
    setDriving(false);
}

void Bridge::setVideoEndpoint(const QString &baseUrl)
{
    m_videoBase = baseUrl;
}

QString Bridge::videoFrameUrl() const
{
    QString base = m_videoBase;
    if (base.isEmpty())
        base = QStringLiteral("http://127.0.0.1:8810");   // per-session engine default
    if (base.endsWith(QLatin1Char('/')))
        base.chop(1);
    return base + QStringLiteral("/video/frame?which=agent");
}

void Bridge::mirrorStart()
{
    if (m_mirroring)
        return;
    setMirroring(true);
    // Ask the daemon to begin mirroring on the device channel too (biometric
    // gated there); locally we just poll the engine for the preview.
    if (!m_coworkerSessionId.isEmpty()) {
        QVariantMap params;
        params.insert(QStringLiteral("session_id"), m_coworkerSessionId);
        request(QStringLiteral("mirror.start"), params);
    }
    m_frameTimer->start();
    pollFrame();
}

void Bridge::mirrorStop()
{
    if (!m_mirroring && !m_frameTimer->isActive())
        return;
    m_frameTimer->stop();
    if (m_frameReply) {
        m_frameReply->abort();
        m_frameReply = nullptr;
    }
    if (!m_coworkerSessionId.isEmpty()) {
        QVariantMap params;
        params.insert(QStringLiteral("session_id"), m_coworkerSessionId);
        request(QStringLiteral("mirror.stop"), params);
    }
    if (m_frameProvider)
        m_frameProvider->clear();
    setMirroring(false);
}

void Bridge::pollFrame()
{
    // Skip if a request is already in flight (avoid pile-up on a slow engine).
    if (m_frameReply)
        return;
    QNetworkRequest req{ QUrl(videoFrameUrl()) };
    if (!m_videoBearer.isEmpty())
        req.setRawHeader("Authorization",
                         QByteArray("Bearer ") + m_videoBearer.toUtf8());
    req.setTransferTimeout(2000);
    m_frameReply = m_net->get(req);
    connect(m_frameReply, &QNetworkReply::finished, this, [this]() {
        QNetworkReply *r = m_frameReply;
        m_frameReply = nullptr;
        onFrameReplyFinished(r);
    });
}

void Bridge::onFrameReplyFinished(QNetworkReply *reply)
{
    if (!reply)
        return;
    reply->deleteLater();
    if (reply->error() != QNetworkReply::NoError)
        return;   // transient; the timer will retry. No error toast for video.
    const QByteArray body = reply->readAll();
    if (body.isEmpty() || !m_frameProvider)
        return;
    if (m_frameProvider->setFrame(body)) {
        ++m_frameSeq;
        emit frameReady(m_frameSeq);
    }
}

// agent_pointer.jsonl fallback tail ------------------------------------------

void Bridge::startPointerTail()
{
    if (m_pointerWatcher)
        return;
    const QString base = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation);
    const QString path = (base.isEmpty() ? QDir::homePath() + QStringLiteral("/.local/share")
                                         : base)
                         + QStringLiteral("/jarvis/agent_pointer.jsonl");
    // Start reading from the end so we only see new pointer events.
    QFileInfo fi(path);
    m_pointerOffset = fi.exists() ? fi.size() : 0;
    m_pointerWatcher = new QFileSystemWatcher(this);
    if (fi.exists())
        m_pointerWatcher->addPath(path);
    // Also watch the directory so we pick the file up when it is first created.
    const QString dir = fi.absolutePath();
    if (QFileInfo::exists(dir))
        m_pointerWatcher->addPath(dir);
    connect(m_pointerWatcher, &QFileSystemWatcher::fileChanged,
            this, &Bridge::readPointerTail);
    connect(m_pointerWatcher, &QFileSystemWatcher::directoryChanged, this,
            [this, path]() {
        if (QFileInfo::exists(path)
            && !m_pointerWatcher->files().contains(path)) {
            m_pointerWatcher->addPath(path);
            readPointerTail();
        }
    });
}

void Bridge::stopPointerTail()
{
    if (!m_pointerWatcher)
        return;
    m_pointerWatcher->deleteLater();
    m_pointerWatcher = nullptr;
    m_pointerOffset = 0;
}

void Bridge::readPointerTail()
{
    const QString base = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation);
    const QString path = (base.isEmpty() ? QDir::homePath() + QStringLiteral("/.local/share")
                                         : base)
                         + QStringLiteral("/jarvis/agent_pointer.jsonl");
    QFile f(path);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
        return;
    // Truncation/rotation guard: if the file shrank, restart from the top.
    if (f.size() < m_pointerOffset)
        m_pointerOffset = 0;
    if (!f.seek(m_pointerOffset))
        return;
    const QByteArray chunk = f.readAll();
    m_pointerOffset = f.pos();
    // Some watchers drop the path after a change event; re-add to keep watching.
    if (m_pointerWatcher && !m_pointerWatcher->files().contains(path))
        m_pointerWatcher->addPath(path);

    for (const QByteArray &lineRaw : chunk.split('\n')) {
        const QByteArray line = lineRaw.trimmed();
        if (line.isEmpty())
            continue;
        QJsonParseError perr;
        const QJsonDocument d = QJsonDocument::fromJson(line, &perr);
        if (perr.error != QJsonParseError::NoError || !d.isObject())
            continue;
        const QJsonObject o = d.object();
        // The engine writes screen-space x,y; normalize if a w/h is present,
        // otherwise pass nx/ny straight through if already normalized.
        double nx = o.value(QStringLiteral("nx")).toDouble(-1.0);
        double ny = o.value(QStringLiteral("ny")).toDouble(-1.0);
        if (nx < 0.0 || ny < 0.0) {
            const double x = o.value(QStringLiteral("x")).toDouble();
            const double y = o.value(QStringLiteral("y")).toDouble();
            const double w = o.value(QStringLiteral("w")).toDouble(0.0);
            const double h = o.value(QStringLiteral("h")).toDouble(0.0);
            nx = (w > 0.0) ? x / w : x;
            ny = (h > 0.0) ? y / h : y;
        }
        const QString action = o.value(QStringLiteral("kind")).toString(
            o.value(QStringLiteral("action")).toString(QStringLiteral("move")));
        const QString button = o.value(QStringLiteral("button")).toString();
        emit agentPointer(nx, ny, action, button);
    }
}

bool Bridge::handleComputerEvent(const QString &sessionId, const QVariantMap &ev)
{
    const QString kind = ev.value(QStringLiteral("kind")).toString();
    if (kind == QStringLiteral("agent_pointer")) {
        // Daemon-forwarded agent pointer (preferred over the file tail). The
        // values arrive as a QVariantMap, so coerce with QVariant::toDouble()
        // (which has no default-value overload) and substitute defaults manually.
        double nx = ev.contains(QStringLiteral("nx")) ? ev.value(QStringLiteral("nx")).toDouble() : -1.0;
        double ny = ev.contains(QStringLiteral("ny")) ? ev.value(QStringLiteral("ny")).toDouble() : -1.0;
        if (nx < 0.0 || ny < 0.0) {
            const double x = ev.value(QStringLiteral("x")).toDouble();
            const double y = ev.value(QStringLiteral("y")).toDouble();
            const double w = ev.value(QStringLiteral("w")).toDouble();
            const double h = ev.value(QStringLiteral("h")).toDouble();
            nx = (w > 0.0) ? x / w : x;
            ny = (h > 0.0) ? y / h : y;
        }
        QString action = ev.value(QStringLiteral("action")).toString();
        if (action.isEmpty())
            action = QStringLiteral("move");
        const QString button = ev.value(QStringLiteral("button")).toString();
        emit agentPointer(nx, ny, action, button);
        return true;
    }
    if (kind == QStringLiteral("driving.state") || kind == QStringLiteral("driving")) {
        setDriving(ev.value(QStringLiteral("active")).toBool());
        return true;
    }
    if (kind == QStringLiteral("mirror.state")) {
        const QString engineUrl = ev.value(QStringLiteral("engine_url")).toString();
        if (!engineUrl.isEmpty())
            setVideoEndpoint(engineUrl);
        if (ev.value(QStringLiteral("active")).toBool()) {
            if (sessionId == m_coworkerSessionId && !m_mirroring)
                mirrorStart();
        } else {
            mirrorStop();
        }
        return true;
    }
    return false;
}

void Bridge::onTextMessageReceived(const QString &message)
{
    QJsonParseError perr;
    const QJsonDocument doc = QJsonDocument::fromJson(message.toUtf8(), &perr);
    if (perr.error != QJsonParseError::NoError || !doc.isObject()) {
        emit errorOccurred(QStringLiteral("malformed frame: ") + perr.errorString());
        return;
    }
    const QJsonObject obj = doc.object();

    // Unsolicited event frame.
    if (obj.value(QStringLiteral("event")).toString() == QStringLiteral("session.event")) {
        const QJsonObject data = obj.value(QStringLiteral("data")).toObject();
        const QString sid = data.value(QStringLiteral("session_id")).toString();
        const QJsonObject ev = data.value(QStringLiteral("ev")).toObject();

        QVariantMap evMap = ev.toVariantMap();
        // COMPUTER-page events (agent_pointer / driving.state / mirror.state) are
        // consumed by the overlay + video poller and are NOT chat transcript rows.
        if (handleComputerEvent(sid, evMap))
            return;
        // Fold the session id in so the UI can route by session.
        evMap.insert(QStringLiteral("session_id"), sid);
        emit sessionEvent(evMap);
        return;
    }

    // Response frame (has an id).
    if (obj.contains(QStringLiteral("id")) && !obj.value(QStringLiteral("id")).isNull()) {
        const int id = obj.value(QStringLiteral("id")).toInt();
        const bool ok = obj.value(QStringLiteral("ok")).toBool();
        const QVariantMap result = obj.value(QStringLiteral("result")).toObject().toVariantMap();
        const QVariantMap error = obj.value(QStringLiteral("error")).toObject().toVariantMap();
        handleResponse(id, ok, result, error);
        return;
    }
}

void Bridge::handleResponse(int id, bool ok, const QVariantMap &result, const QVariantMap &error)
{
    const QString method = m_pending.take(id);
    const QString ctx = m_pendingCtx.take(id);

    if (!ok) {
        const QString msg = error.value(QStringLiteral("message")).toString();
        const QString code = error.value(QStringLiteral("code")).toString();
        if (method == QStringLiteral("session.history"))
            m_openingSession = false;
        // mcp.test failures surface through mcpTested, not a generic error toast.
        if (method == QStringLiteral("mcp.test")) {
            emit mcpTested(ctx, false, 0, msg.isEmpty() ? code : msg);
            return;
        }
        // Forward-compatible COMPUTER-page control methods: the daemon may not
        // implement these yet (Wave 5 lands them). Swallow "unknown_method" so the
        // desktop preview/overlay degrade gracefully instead of toasting an error.
        if (code == QStringLiteral("unknown_method")
            && (method == QStringLiteral("mirror.start")
                || method == QStringLiteral("mirror.stop")
                || method == QStringLiteral("session.set_target"))) {
            return;
        }
        // Memory + skills (Contract A v3) land daemon-side in Wave 6. Until then
        // the daemon answers unknown_method; degrade the pages to a clean empty
        // state instead of a generic error toast.
        if (code == QStringLiteral("unknown_method")
            && (method.startsWith(QStringLiteral("memory."))
                || method.startsWith(QStringLiteral("skills.")))) {
            if (method == QStringLiteral("memory.list"))
                emit memoriesListed(QVariantList(), false);
            else if (method == QStringLiteral("memory.search"))
                emit memoriesListed(QVariantList(), true);
            else if (method == QStringLiteral("skills.list"))
                emit skillsListed(QVariantList());
            else if (method == QStringLiteral("skills.today"))
                emit todayDigest(QString());
            return;
        }
        emit errorOccurred(QStringLiteral("%1 failed: [%2] %3")
                               .arg(method.isEmpty() ? QStringLiteral("request") : method, code, msg));
        return;
    }

    if (method == QStringLiteral("session.create")) {
        const QString sid = result.value(QStringLiteral("session_id")).toString();
        if (!sid.isEmpty()) {
            m_sessionId = sid;
            emit sessionIdChanged();
            setStatus(QStringLiteral("session ready"));

            // The engine url for this session's per-session computer-use engine,
            // if the daemon reports it (else the per-session-port default is used).
            const QString engineUrl = result.value(QStringLiteral("engine_url")).toString();
            if (!engineUrl.isEmpty())
                setVideoEndpoint(engineUrl);

            if (ctx == QStringLiteral("coworker:agent")) {
                // Co-worker on the NESTED agent desktop: wire it up + start the
                // local mirror preview immediately (the user keeps their screen).
                setCoworkerSessionId(sid);
                emit coworkerStarted(sid);
                mirrorStart();
            } else if (ctx == QStringLiteral("coworker:real")) {
                // REAL-screen take-over: the daemon now runs its approval flow;
                // `driving` stays false until it confirms via a driving.state
                // event. Surface the pending request so the UI can show it.
                emit takeOverRequested(sid);
                // If the daemon reports the take-over is already active (auto-
                // approved tier), honor it.
                if (result.value(QStringLiteral("driving")).toBool())
                    setDriving(true);
            }
        }
    } else if (method == QStringLiteral("model.list")) {
        QStringList models;
        const QVariant raw = result.value(QStringLiteral("models"));
        for (const QVariant &v : raw.toList())
            models << v.toString();
        const QString brain = result.value(QStringLiteral("brain")).toString();
        emit modelsListed(brain, models);
    } else if (method == QStringLiteral("settings.get")) {
        emit settingsLoaded(result);
    } else if (method == QStringLiteral("settings.set")) {
        emit settingsSaved();
    } else if (method == QStringLiteral("mcp.list")) {
        emit mcpListed(result.value(QStringLiteral("servers")).toList());
    } else if (method == QStringLiteral("mcp.add")
               || method == QStringLiteral("mcp.remove")
               || method == QStringLiteral("mcp.set_enabled")) {
        emit mcpChanged();
        listMcp(); // refresh the list after a mutation
    } else if (method == QStringLiteral("mcp.test")) {
        emit mcpTested(ctx,
                       result.value(QStringLiteral("ok")).toBool(),
                       result.value(QStringLiteral("tools_count")).toInt(),
                       result.value(QStringLiteral("error")).toString());
    } else if (method == QStringLiteral("plugins.catalog")) {
        emit pluginsListed(result.value(QStringLiteral("plugins")).toList());
    } else if (method == QStringLiteral("plugins.install")
               || method == QStringLiteral("plugins.set_enabled")
               || method == QStringLiteral("plugins.remove")) {
        emit pluginsChanged();
        loadPlugins(); // refresh the catalog after a mutation
    } else if (method == QStringLiteral("session.list")) {
        emit sessionsListed(result.value(QStringLiteral("sessions")).toList());
    } else if (method == QStringLiteral("session.history")) {
        // events: [{seq,ts,ev:{kind,...}}] — fold the inner ev out for QML.
        QVariantList events;
        for (const QVariant &v : result.value(QStringLiteral("events")).toList()) {
            const QVariantMap row = v.toMap();
            QVariantMap evm = row.value(QStringLiteral("ev")).toMap();
            evm.insert(QStringLiteral("seq"), row.value(QStringLiteral("seq")));
            events << evm;
        }
        const QString sid = ctx.isEmpty()
                                ? result.value(QStringLiteral("session")).toMap()
                                      .value(QStringLiteral("id")).toString()
                                : ctx;
        emit sessionHistory(sid, events);
        m_openingSession = false;
    } else if (method == QStringLiteral("memory.list")) {
        emit memoriesListed(result.value(QStringLiteral("memories")).toList(), false);
    } else if (method == QStringLiteral("memory.search")) {
        emit memoriesListed(result.value(QStringLiteral("memories")).toList(), true);
    } else if (method == QStringLiteral("memory.add")
               || method == QStringLiteral("memory.remove")) {
        emit memoryChanged();
        memoryList(); // refresh the list after a mutation
    } else if (method == QStringLiteral("skills.list")) {
        emit skillsListed(result.value(QStringLiteral("skills")).toList());
    } else if (method == QStringLiteral("skills.get")) {
        emit skillLoaded(ctx,
                         result.value(QStringLiteral("frontmatter")).toMap(),
                         result.value(QStringLiteral("body")).toString(),
                         result.value(QStringLiteral("path")).toString());
    } else if (method == QStringLiteral("skills.create")
               || method == QStringLiteral("skills.remove")) {
        emit skillsChanged();
        skillsList(); // re-index after a self-authoring write / removal
    } else if (method == QStringLiteral("skills.invoke")) {
        emit skillInvoked(ctx, result.value(QStringLiteral("message")).toString());
    } else if (method == QStringLiteral("skills.today")) {
        emit todayDigest(result.value(QStringLiteral("digest")).toString());
    } else if (method == QStringLiteral("devices.pair_start")) {
        // { code, payload, qr_svg, expires_at }
        const QString qrSvg = result.value(QStringLiteral("qr_svg")).toString();
        const QString code = result.value(QStringLiteral("code")).toString();
        const QString payload = result.value(QStringLiteral("payload")).toString();
        // expires_at may arrive as epoch seconds (number) or an ISO string; the UI
        // only needs a numeric epoch for the countdown, so coerce defensively.
        const QVariant exp = result.value(QStringLiteral("expires_at"));
        emit pairingStarted(qrSvg, code, payload, exp.toDouble());
    } else if (method == QStringLiteral("devices.list")) {
        emit devicesListed(result.value(QStringLiteral("devices")).toList());
    } else if (method == QStringLiteral("devices.revoke")) {
        emit devicesChanged();
        devicesList(); // refresh the paired-device list after a revoke
    }
    // ping / session.send / session.cancel / approval.respond: ack only.
}
