#include "Bridge.h"

#include <QWebSocket>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QJsonValue>
#include <QFile>
#include <QDir>
#include <QStandardPaths>
#include <QUrl>
#include <QUrlQuery>
#include <QDebug>

Bridge::Bridge(QObject *parent)
    : QObject(parent)
    , m_socket(new QWebSocket(QString(), QWebSocketProtocol::VersionLatest, this))
{
    connect(m_socket, &QWebSocket::connected, this, &Bridge::onConnected);
    connect(m_socket, &QWebSocket::disconnected, this, &Bridge::onDisconnected);
    connect(m_socket, &QWebSocket::textMessageReceived, this, &Bridge::onTextMessageReceived);
    connect(m_socket, QOverload<QAbstractSocket::SocketError>::of(&QWebSocket::errorOccurred),
            this, &Bridge::onSocketError);
}

Bridge::~Bridge() = default;

QString Bridge::readControlToken()
{
    // ~/.config/jarvis/control_token  (0600, auto-generated by jarvisd on first start).
    QString base = QStandardPaths::writableLocation(QStandardPaths::ConfigLocation);
    if (base.isEmpty())
        base = QDir::homePath() + QStringLiteral("/.config");
    const QString path = base + QStringLiteral("/jarvis/control_token");

    QFile f(path);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
        return QString();
    QString tok = QString::fromUtf8(f.readAll()).trimmed();
    return tok;
}

QString Bridge::controlUrl()
{
    QUrl url;
    url.setScheme(QStringLiteral("ws"));
    url.setHost(QStringLiteral("127.0.0.1"));
    url.setPort(8795);
    url.setPath(QStringLiteral("/control/ws"));

    QUrlQuery q;
    q.addQueryItem(QStringLiteral("token"), readControlToken());
    url.setQuery(q);
    return url.toString();
}

void Bridge::setStatus(const QString &s)
{
    if (m_status == s)
        return;
    m_status = s;
    emit statusChanged();
}

void Bridge::connectToDaemon()
{
    if (m_connected) {
        return;
    }
    const QString tok = readControlToken();
    if (tok.isEmpty()) {
        setStatus(QStringLiteral("no token"));
        emit errorOccurred(QStringLiteral("control_token not found at ~/.config/jarvis/control_token"));
        // Still attempt connect; daemon may reject, which surfaces a clear error.
    }
    setStatus(QStringLiteral("connecting"));
    m_socket->open(QUrl(controlUrl()));
}

void Bridge::onConnected()
{
    m_connected = true;
    emit connectedChanged();
    setStatus(QStringLiteral("connected"));
    // Liveness check per Contract A.
    request(QStringLiteral("ping"), {});
}

void Bridge::onDisconnected()
{
    const bool was = m_connected;
    m_connected = false;
    if (was)
        emit connectedChanged();
    setStatus(QStringLiteral("disconnected"));
}

void Bridge::onSocketError()
{
    setStatus(QStringLiteral("error"));
    emit errorOccurred(m_socket->errorString());
}

int Bridge::nextId()
{
    return ++m_idCounter;
}

void Bridge::send(const QString &method, const QVariantMap &params, int id)
{
    QJsonObject obj;
    obj.insert(QStringLiteral("v"), 1);
    obj.insert(QStringLiteral("id"), id);
    obj.insert(QStringLiteral("method"), method);
    obj.insert(QStringLiteral("params"), QJsonObject::fromVariantMap(params));

    const QByteArray payload = QJsonDocument(obj).toJson(QJsonDocument::Compact);
    if (m_socket->state() != QAbstractSocket::ConnectedState) {
        emit errorOccurred(QStringLiteral("not connected: dropped ") + method);
        return;
    }
    m_socket->sendTextMessage(QString::fromUtf8(payload));
}

int Bridge::request(const QString &method, const QVariantMap &params, const QString &ctx)
{
    const int id = nextId();
    m_pending.insert(id, method);
    if (!ctx.isEmpty())
        m_pendingCtx.insert(id, ctx);
    send(method, params, id);
    return id;
}

void Bridge::createSession(const QString &profile, const QString &brain, const QString &model)
{
    QVariantMap params;
    params.insert(QStringLiteral("profile"), profile.isEmpty() ? QStringLiteral("coder") : profile);
    params.insert(QStringLiteral("brain"), brain.isEmpty() ? QStringLiteral("codex") : brain);
    if (!model.isEmpty())
        params.insert(QStringLiteral("model"), model);
    request(QStringLiteral("session.create"), params);
}

void Bridge::sendMessage(const QString &text)
{
    if (m_sessionId.isEmpty()) {
        emit errorOccurred(QStringLiteral("no active session; create one first"));
        return;
    }
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), m_sessionId);
    params.insert(QStringLiteral("text"), text);
    request(QStringLiteral("session.send"), params);
}

void Bridge::cancelSession()
{
    if (m_sessionId.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), m_sessionId);
    request(QStringLiteral("session.cancel"), params);
}

void Bridge::respondApproval(const QString &approvalId, const QString &decision)
{
    if (m_sessionId.isEmpty()) {
        emit errorOccurred(QStringLiteral("no active session for approval response"));
        return;
    }
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), m_sessionId);
    params.insert(QStringLiteral("approval_id"), approvalId);
    params.insert(QStringLiteral("decision"), decision);
    request(QStringLiteral("approval.respond"), params);
}

void Bridge::listModels(const QString &brain)
{
    QVariantMap params;
    params.insert(QStringLiteral("brain"), brain.isEmpty() ? QStringLiteral("codex") : brain);
    request(QStringLiteral("model.list"), params);
}

// ---- Contract A v2 ---------------------------------------------------------

void Bridge::openSession(const QString &sessionId)
{
    if (sessionId.isEmpty())
        return;
    m_sessionId = sessionId;
    emit sessionIdChanged();
    setStatus(QStringLiteral("session ready"));
    emit sessionOpened(sessionId);
    // Load this session's history so the Chat page can replay it.
    m_openingSession = true;
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), sessionId);
    request(QStringLiteral("session.history"), params, sessionId);
}

void Bridge::loadSettings()
{
    request(QStringLiteral("settings.get"), {});
}

void Bridge::saveSettings(const QVariantMap &patch)
{
    QVariantMap params;
    params.insert(QStringLiteral("patch"), patch);
    request(QStringLiteral("settings.set"), params);
}

void Bridge::listMcp()
{
    request(QStringLiteral("mcp.list"), {});
}

void Bridge::addMcp(const QVariantMap &server)
{
    request(QStringLiteral("mcp.add"), server);
}

void Bridge::removeMcp(const QString &id)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("mcp.remove"), params);
}

void Bridge::setMcpEnabled(const QString &id, bool enabled)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    params.insert(QStringLiteral("enabled"), enabled);
    request(QStringLiteral("mcp.set_enabled"), params);
}

void Bridge::testMcp(const QString &id)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("mcp.test"), params, id);
}

void Bridge::loadPlugins()
{
    request(QStringLiteral("plugins.catalog"), {});
}

void Bridge::installPlugin(const QString &id)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("plugins.install"), params);
}

void Bridge::setPluginEnabled(const QString &id, bool enabled)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    params.insert(QStringLiteral("enabled"), enabled);
    request(QStringLiteral("plugins.set_enabled"), params);
}

void Bridge::removePlugin(const QString &id)
{
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("plugins.remove"), params);
}

void Bridge::listSessions()
{
    request(QStringLiteral("session.list"), {});
}

void Bridge::loadSessionHistory(const QString &sessionId)
{
    QVariantMap params;
    params.insert(QStringLiteral("session_id"), sessionId);
    request(QStringLiteral("session.history"), params, sessionId);
}

// ---- Devices (pairing) -----------------------------------------------------

void Bridge::devicesPairStart()
{
    request(QStringLiteral("devices.pair_start"), {});
}

void Bridge::devicesList()
{
    request(QStringLiteral("devices.list"), {});
}

void Bridge::devicesRevoke(const QString &id)
{
    if (id.isEmpty())
        return;
    QVariantMap params;
    params.insert(QStringLiteral("id"), id);
    request(QStringLiteral("devices.revoke"), params);
}

void Bridge::onTextMessageReceived(const QString &message)
{
    QJsonParseError perr;
    const QJsonDocument doc = QJsonDocument::fromJson(message.toUtf8(), &perr);
    if (perr.error != QJsonParseError::NoError || !doc.isObject()) {
        emit errorOccurred(QStringLiteral("malformed frame: ") + perr.errorString());
        return;
    }
    const QJsonObject obj = doc.object();

    // Unsolicited event frame.
    if (obj.value(QStringLiteral("event")).toString() == QStringLiteral("session.event")) {
        const QJsonObject data = obj.value(QStringLiteral("data")).toObject();
        const QString sid = data.value(QStringLiteral("session_id")).toString();
        const QJsonObject ev = data.value(QStringLiteral("ev")).toObject();

        QVariantMap evMap = ev.toVariantMap();
        // Fold the session id in so the UI can route by session.
        evMap.insert(QStringLiteral("session_id"), sid);
        emit sessionEvent(evMap);
        return;
    }

    // Response frame (has an id).
    if (obj.contains(QStringLiteral("id")) && !obj.value(QStringLiteral("id")).isNull()) {
        const int id = obj.value(QStringLiteral("id")).toInt();
        const bool ok = obj.value(QStringLiteral("ok")).toBool();
        const QVariantMap result = obj.value(QStringLiteral("result")).toObject().toVariantMap();
        const QVariantMap error = obj.value(QStringLiteral("error")).toObject().toVariantMap();
        handleResponse(id, ok, result, error);
        return;
    }
}

void Bridge::handleResponse(int id, bool ok, const QVariantMap &result, const QVariantMap &error)
{
    const QString method = m_pending.take(id);
    const QString ctx = m_pendingCtx.take(id);

    if (!ok) {
        const QString msg = error.value(QStringLiteral("message")).toString();
        const QString code = error.value(QStringLiteral("code")).toString();
        if (method == QStringLiteral("session.history"))
            m_openingSession = false;
        // mcp.test failures surface through mcpTested, not a generic error toast.
        if (method == QStringLiteral("mcp.test")) {
            emit mcpTested(ctx, false, 0, msg.isEmpty() ? code : msg);
            return;
        }
        emit errorOccurred(QStringLiteral("%1 failed: [%2] %3")
                               .arg(method.isEmpty() ? QStringLiteral("request") : method, code, msg));
        return;
    }

    if (method == QStringLiteral("session.create")) {
        const QString sid = result.value(QStringLiteral("session_id")).toString();
        if (!sid.isEmpty()) {
            m_sessionId = sid;
            emit sessionIdChanged();
            setStatus(QStringLiteral("session ready"));
        }
    } else if (method == QStringLiteral("model.list")) {
        QStringList models;
        const QVariant raw = result.value(QStringLiteral("models"));
        for (const QVariant &v : raw.toList())
            models << v.toString();
        const QString brain = result.value(QStringLiteral("brain")).toString();
        emit modelsListed(brain, models);
    } else if (method == QStringLiteral("settings.get")) {
        emit settingsLoaded(result);
    } else if (method == QStringLiteral("settings.set")) {
        emit settingsSaved();
    } else if (method == QStringLiteral("mcp.list")) {
        emit mcpListed(result.value(QStringLiteral("servers")).toList());
    } else if (method == QStringLiteral("mcp.add")
               || method == QStringLiteral("mcp.remove")
               || method == QStringLiteral("mcp.set_enabled")) {
        emit mcpChanged();
        listMcp(); // refresh the list after a mutation
    } else if (method == QStringLiteral("mcp.test")) {
        emit mcpTested(ctx,
                       result.value(QStringLiteral("ok")).toBool(),
                       result.value(QStringLiteral("tools_count")).toInt(),
                       result.value(QStringLiteral("error")).toString());
    } else if (method == QStringLiteral("plugins.catalog")) {
        emit pluginsListed(result.value(QStringLiteral("plugins")).toList());
    } else if (method == QStringLiteral("plugins.install")
               || method == QStringLiteral("plugins.set_enabled")
               || method == QStringLiteral("plugins.remove")) {
        emit pluginsChanged();
        loadPlugins(); // refresh the catalog after a mutation
    } else if (method == QStringLiteral("session.list")) {
        emit sessionsListed(result.value(QStringLiteral("sessions")).toList());
    } else if (method == QStringLiteral("session.history")) {
        // events: [{seq,ts,ev:{kind,...}}] — fold the inner ev out for QML.
        QVariantList events;
        for (const QVariant &v : result.value(QStringLiteral("events")).toList()) {
            const QVariantMap row = v.toMap();
            QVariantMap evm = row.value(QStringLiteral("ev")).toMap();
            evm.insert(QStringLiteral("seq"), row.value(QStringLiteral("seq")));
            events << evm;
        }
        const QString sid = ctx.isEmpty()
                                ? result.value(QStringLiteral("session")).toMap()
                                      .value(QStringLiteral("id")).toString()
                                : ctx;
        emit sessionHistory(sid, events);
        m_openingSession = false;
    } else if (method == QStringLiteral("devices.pair_start")) {
        // { code, payload, qr_svg, expires_at }
        const QString qrSvg = result.value(QStringLiteral("qr_svg")).toString();
        const QString code = result.value(QStringLiteral("code")).toString();
        const QString payload = result.value(QStringLiteral("payload")).toString();
        // expires_at may arrive as epoch seconds (number) or an ISO string; the UI
        // only needs a numeric epoch for the countdown, so coerce defensively.
        const QVariant exp = result.value(QStringLiteral("expires_at"));
        emit pairingStarted(qrSvg, code, payload, exp.toDouble());
    } else if (method == QStringLiteral("devices.list")) {
        emit devicesListed(result.value(QStringLiteral("devices")).toList());
    } else if (method == QStringLiteral("devices.revoke")) {
        emit devicesChanged();
        devicesList(); // refresh the paired-device list after a revoke
    }
    // ping / session.send / session.cancel / approval.respond: ack only.
}
