"""Configuration for the Jarvis-MCP server.

This server is the single MCP endpoint that fronts the whole Jarvis stack:
- the jarvisd *control* WebSocket (Contract A, ws://127.0.0.1:8795/control/ws),
  reached with the bearer at ~/.config/jarvis/control_token;
- the computer-use FastMCP engine (:8794), re-exported under a jarvis namespace,
  reached with the bearer at ~/.computer-use/config.yaml.

Its own inbound bearer lives at ~/.config/jarvis/jarvis_mcp_token (0600,
auto-generated on first start). The token is the gate (tailnet model — same
rationale as computer-use/phone-installer/vm-agent), so we bind everywhere by
default and survive tailscale being down; /health is the only open path.
"""

import os
import secrets
from pathlib import Path

import yaml

# --- this server -----------------------------------------------------------
# JARVIS_CONFIG_DIR env points at a second isolated profile (jarvis#76 item 15).
JARVIS_CONFIG_DIR = Path(os.environ.get("JARVIS_CONFIG_DIR")
                         or str(Path.home() / ".config" / "jarvis"))
TOKEN_FILE = JARVIS_CONFIG_DIR / "jarvis_mcp_token"

DEFAULT_HOST = "0.0.0.0"
# 8790 project-tracker, 8791 phone-installer, 8792 phone file server, 8794
# computer-use, 8795 jarvisd control, 8796 jarvisd device -> 8797 is free.
DEFAULT_PORT = 8797
ADVERTISE_HOST = "127.0.0.1"

# --- jarvisd control WS (Contract A) ---------------------------------------
CONTROL_TOKEN_FILE = JARVIS_CONFIG_DIR / "control_token"
DEFAULT_CONTROL_WS = "ws://127.0.0.1:8795/control/ws"

# --- computer-use engine (re-exported) -------------------------------------
COMPUTER_USE_CONFIG = Path.home() / ".computer-use" / "config.yaml"
# Loopback by default (this server runs on the same box as the engine); the
# advertise_host in the engine's own config is honoured if loopback is down.
DEFAULT_COMPUTER_USE_MCP = "http://127.0.0.1:8794/mcp"


def _env(name: str, default: str) -> str:
    v = os.environ.get(name)
    return v if v else default


def host() -> str:
    return _env("JARVIS_MCP_HOST", DEFAULT_HOST)


def port() -> int:
    try:
        return int(_env("JARVIS_MCP_PORT", str(DEFAULT_PORT)))
    except ValueError:
        return DEFAULT_PORT


def control_ws_url() -> str:
    """jarvisd control WS, with the ?token= appended (Contract A auth)."""
    base = _env("JARVIS_CONTROL_WS", DEFAULT_CONTROL_WS)
    token = control_token()
    if not token:
        return base
    sep = "&" if "?" in base else "?"
    return f"{base}{sep}token={token}"


def control_token() -> str:
    """Read the jarvisd control token (auto-generated by jarvisd on first run).

    Env override JARVIS_CONTROL_TOKEN wins (handy for tests / mock daemons).
    """
    env = os.environ.get("JARVIS_CONTROL_TOKEN")
    if env:
        return env.strip()
    try:
        return CONTROL_TOKEN_FILE.read_text().strip()
    except OSError:
        return ""


def get_bearer_token() -> str:
    """This server's inbound bearer; auto-generate a 0600 token on first run.

    Env override JARVIS_MCP_TOKEN wins (tests / ephemeral runs without touching
    the on-disk token).
    """
    env = os.environ.get("JARVIS_MCP_TOKEN")
    if env:
        return env.strip()
    try:
        existing = TOKEN_FILE.read_text().strip()
        if existing:
            return existing
    except OSError:
        pass
    JARVIS_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    token = secrets.token_urlsafe(32)
    TOKEN_FILE.write_text(token)
    os.chmod(TOKEN_FILE, 0o600)
    print(f"jarvis-mcp: created bearer token at {TOKEN_FILE}")
    return token


def computer_use_endpoint() -> tuple[str, str]:
    """(mcp_url, bearer) for the computer-use engine we re-export.

    URL: JARVIS_CU_MCP env > loopback default. Bearer: JARVIS_CU_TOKEN env >
    ~/.computer-use/config.yaml. Returning ("","") disables re-export so the
    server still starts (Jarvis-only) when the engine isn't configured.
    """
    url = os.environ.get("JARVIS_CU_MCP", DEFAULT_COMPUTER_USE_MCP)
    token = os.environ.get("JARVIS_CU_TOKEN", "")
    if not token:
        try:
            with open(COMPUTER_USE_CONFIG) as f:
                cfg = yaml.safe_load(f) or {}
            token = str(cfg.get("bearer_token", "") or "")
        except OSError:
            token = ""
    return url, token
