"""Per-VM JARVIS.md profiles — CLAUDE.md, but for a VM.

One markdown file per guest under <state>/vms/<vmid>.md. The file is shared
ground truth between three writers with strict lanes:

  ## Purpose / ## Preferences  — the USER's (via the interview flow / Outpost
                                 page); the agent only writes here when
                                 recording a user's answer verbatim.
  ## Observed                  — the SCOUT's; regenerated wholesale on every
                                 scan. Never hand-edit, never preserved.
  ## Notes                     — the AGENT's own durable observations.

update_observed() must therefore preserve every byte of every section it
doesn't own — a re-scan that eats the user's Purpose answer would undo the
whole interview flow. All functions take the profiles dir explicitly (tests
pass tmp_path; the tools layer passes config.PROFILES_DIR).
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

USER_SECTIONS = ("Purpose", "Preferences", "Notes")
_CANONICAL_ORDER = ("Purpose", "Preferences", "Observed", "Notes")
_META_RE = re.compile(r"<!--\s*jarvis:meta\s+(\{.*?\})\s*-->")

_PURPOSE_PLACEHOLDER = "(unknown — the agent will ask)"
_PREFS_PLACEHOLDER = "(none recorded)"

# Per-list caps keep a profile a few KB so proxmox.vm_profile reads stay far
# under the outpost exec output cap even for a busy guest.
_OBSERVED_CAPS = {"services": 25, "ports": 25, "docker": 15, "disk": 12,
                  "top": 12, "mem": 3}


def profile_path(profiles_dir: Path, vmid: int) -> Path:
    return profiles_dir / f"{int(vmid)}.md"


def load(profiles_dir: Path, vmid: int) -> str:
    try:
        return profile_path(profiles_dir, vmid).read_text()
    except OSError:
        return ""


def read_meta(text: str) -> dict:
    m = _META_RE.search(text or "")
    if not m:
        return {}
    try:
        meta = json.loads(m.group(1))
        return meta if isinstance(meta, dict) else {}
    except ValueError:
        return {}


def parse_sections(text: str) -> dict[str, str]:
    """{section name: exact content between headers} in file order. The
    preamble (title + meta comment) is NOT a section — it's regenerated on
    every write."""
    sections: dict[str, str] = {}
    current: str | None = None
    buf: list[str] = []
    for line in (text or "").split("\n"):
        if line.startswith("## "):
            if current is not None:
                sections[current] = "\n".join(buf).strip("\n")
            current = line[3:].strip()
            buf = []
        elif current is not None:
            buf.append(line)
    if current is not None:
        sections[current] = "\n".join(buf).strip("\n")
    return sections


def _render_observed(observed: dict, agent: bool | None) -> str:
    hostname = (observed.get("hostname") or [""])[0].strip()
    os_line = ""
    for line in observed.get("os") or []:
        line = line.strip()
        if line.startswith("PRETTY_NAME="):
            os_line = line.split("=", 1)[1].strip().strip('"')
            break
        if not os_line and line:
            os_line = line.strip('"')
    agent_str = "n/a (lxc)" if agent is None else ("yes" if agent else "no")
    lines = ["<!-- auto-generated by scout — do not hand-edit; regenerated wholesale -->",
             f"- OS: {os_line or 'unknown'} · hostname: {hostname or 'unknown'} · "
             f"guest agent: {agent_str}"]
    titles = {"services": "Services", "ports": "Listening ports",
              "docker": "Docker containers", "disk": "Disk", "top": "Top processes",
              "mem": "Memory"}
    for key, title in titles.items():
        rows = observed.get(key) or []
        if not rows:
            continue
        cap = _OBSERVED_CAPS.get(key, 15)
        lines.append(f"### {title}")
        lines.extend(f"- {r.strip()}" for r in rows[:cap])
        if len(rows) > cap:
            lines.append(f"- … {len(rows) - cap} more")
    return "\n".join(lines)


def _render(vmid: int, name: str, kind: str, meta: dict, sections: dict[str, str]) -> str:
    out = [f"# VM {vmid} — {name} ({kind})",
           f"<!-- jarvis:meta {json.dumps(meta, sort_keys=True)} -->", ""]
    emitted = set()
    for sec in _CANONICAL_ORDER:
        if sec in sections:
            out += [f"## {sec}", sections[sec], ""]
            emitted.add(sec)
    for sec, body in sections.items():  # preserve anything nonstandard too
        if sec not in emitted:
            out += [f"## {sec}", body, ""]
    return "\n".join(out).rstrip("\n") + "\n"


def _write(profiles_dir: Path, vmid: int, text: str) -> None:
    profiles_dir.mkdir(parents=True, exist_ok=True)
    path = profile_path(profiles_dir, vmid)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)  # atomic on the same filesystem


def update_observed(profiles_dir: Path, vmid: int, name: str, kind: str,
                    os_family: str, observed: dict, agent: bool | None,
                    now_ms: int) -> str:
    """Regenerate the Observed section (and meta/title), preserving every
    other section byte-for-byte. Creates the skeleton for a new VM."""
    existing = load(profiles_dir, vmid)
    sections = parse_sections(existing)
    sections.setdefault("Purpose", _PURPOSE_PLACEHOLDER)
    sections.setdefault("Preferences", _PREFS_PLACEHOLDER)
    sections.setdefault("Notes", "")
    sections["Observed"] = _render_observed(observed, agent)
    meta = read_meta(existing)
    meta.update({"vmid": int(vmid), "kind": kind, "os_family": os_family,
                 "name": name, "observed_at": int(now_ms), "scout_version": 1})
    text = _render(vmid, name, kind, meta, sections)
    _write(profiles_dir, vmid, text)
    return text


def set_user_section(profiles_dir: Path, vmid: int, section: str, text: str,
                     now_ms: int) -> dict:
    """Write a user-owned section (Purpose/Preferences/Notes). Refuses
    Observed — that lane belongs to the scout."""
    if section not in USER_SECTIONS:
        return {"ok": False,
                "error": f"section must be one of {list(USER_SECTIONS)} "
                        "(Observed is scout-owned)"}
    existing = load(profiles_dir, vmid)
    sections = parse_sections(existing)
    sections.setdefault("Purpose", _PURPOSE_PLACEHOLDER)
    sections.setdefault("Preferences", _PREFS_PLACEHOLDER)
    sections.setdefault("Observed", "(not scouted yet)")
    sections.setdefault("Notes", "")
    sections[section] = (text or "").strip()
    meta = read_meta(existing)
    name = meta.get("name", f"vm-{vmid}")
    kind = meta.get("kind", "qemu")
    meta.setdefault("vmid", int(vmid))
    meta["updated_at"] = int(now_ms)
    _write(profiles_dir, vmid, _render(vmid, name, kind, meta, sections))
    return {"ok": True, "vmid": int(vmid), "section": section}


def is_stale(meta: dict, now_ms: int, stale_days: int = 7) -> bool:
    observed_at = meta.get("observed_at")
    if not observed_at:
        return True
    return (now_ms - int(observed_at)) > stale_days * 24 * 3600 * 1000


def has_purpose(sections: dict[str, str]) -> bool:
    purpose = (sections.get("Purpose") or "").strip()
    return bool(purpose) and purpose != _PURPOSE_PLACEHOLDER


def list_profiles(profiles_dir: Path, now_ms: int, stale_days: int = 7) -> list[dict]:
    """[{vmid, name, kind, observed_at, has_purpose, stale}] for every
    profile on disk — what the agent uses to decide who needs a re-scout or
    an interview question."""
    rows = []
    try:
        paths = sorted(profiles_dir.glob("*.md"))
    except OSError:
        return []
    for path in paths:
        try:
            vmid = int(path.stem)
        except ValueError:
            continue
        text = load(profiles_dir, vmid)
        meta = read_meta(text)
        sections = parse_sections(text)
        rows.append({
            "vmid": vmid,
            "name": meta.get("name", path.stem),
            "kind": meta.get("kind", "qemu"),
            "observed_at": meta.get("observed_at"),
            "has_purpose": has_purpose(sections),
            "stale": is_stale(meta, now_ms, stale_days),
        })
    return rows
